### ISSUE TITLE
favicon 

### ISSUE THREAD

**Issue by yangwao** [kodadot/metaprime-landing#5]
@JKrupinski  all we have for now https://github.com/kodadot/metaprime-presskit/tree/main/v1

**Comment by JKrupinski** [comment]
@yangwao Done, not sure if it's visible enough

**Comment by yangwao** [comment]
![image](https://user-images.githubusercontent.com/5887929/140649541-8a732888-3bd3-4f32-8b34-64db5c78b69b.png)
Good for now for me!
